[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Tag               docker.*
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[OUTPUT]
    Name              splunk
    Match             docker.*
    Host              splunk
    Port              8088
    Splunk_Token      d14ea12a-3a81-432b-801f-257f181ee52f
    TLS               On
    TLS.Verify        Off